# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider 'docker' do |d|
    d.image = 'artemsidorenko/vagrant-environments:ubuntu1404'
    d.has_ssh = true
    d.remains_running = true
  end

  config.vm.provider 'virtualbox' do |_, override|
    override.vm.box = 'bento/ubuntu-14.04'

    # some tools (they are packaged in docker, but probably not here)
    override.vm.provision 'shell', inline: 'apt-get update; apt-get -y install git curl wget'
  end

  config.vm.synced_folder '.', '/vagrant'
  config.vm.synced_folder '../share', '/home/vagrant/share'

  # automatically move to the mounted share directory
  config.vm.provision 'shell', inline: "grep -q 'cd /home/vagrant/share' /home/vagrant/.profile || echo 'cd /home/vagrant/share' >> /home/vagrant/.profile"

  # include some local settings if possible
  if File.exists?('../vagrant.local.rb')
    local_settings = File.read('../vagrant.local.rb')
    eval local_settings
  end
end
